const ProductList = [
  {
    id: 1,
    englishName: "Tomato",
    marathiName: "टोमॅटो",
    hinglishName: "TomaTo",
  },
  {
    id: 2,
    englishName: "Potato",
    marathiName: "बटाटा",
    hinglishName: "Batata",
  },
  { id: 3, englishName: "Onion", marathiName: "कांदा", hinglishName: "Kanda" },
  { id: 4, englishName: "Carrot", marathiName: "गाजर", hinglishName: "Gajar" },
  {
    id: 5,
    englishName: "Brinjal",
    marathiName: "वांगी",
    hinglishName: "Vaangi",
  },
  {
    id: 6,
    englishName: "Cabbage",
    marathiName: "कोबी",
    hinglishName: "banda Kobi",
  },
  {
    id: 7,
    englishName: "Cauliflower",
    marathiName: "फूलकोबी",
    hinglishName: "Phoolkobi",
  },
  {
    id: 8,
    englishName: "Green Peas",
    marathiName: "हिरवे वाटाणे",
    hinglishName: "Hirve Wataane",
  },
  {
    id: 9,
    englishName: "Spinach",
    marathiName: "पालक",
    hinglishName: "PaalaK",
  },
  {
    id: 10,
    englishName: "Fenugreek",
    marathiName: "मेथी",
    hinglishName: "Methi",
  },
  {
    id: 11,
    englishName: "Coriander",
    marathiName: "कोथिंबीर",
    hinglishName: "Kothimbir",
  },
  { id: 12, englishName: "Garlic", marathiName: "लसूण", hinglishName: "Lasun" },
  { id: 13, englishName: "Ginger", marathiName: "आले", hinglishName: "Aale" },
  {
    id: 14,
    englishName: "Bottle Gourd",
    marathiName: "दूधी भोपळा",
    hinglishName: "Doodhi Bhopala",
  },
  {
    id: 15,
    englishName: "Bitter Gourd",
    marathiName: "कारले",
    hinglishName: "Karle",
  },
  {
    id: 16,
    englishName: "Lady Finger",
    marathiName: "भेंडी",
    hinglishName: "Bhendi",
  },
  {
    id: 17,
    englishName: "Drumstick",
    marathiName: "शेवग्याच्या शेंगा",
    hinglishName: "Shevgyachya Shengaa",
  },
  {
    id: 18,
    englishName: "Pumpkin",
    marathiName: "भोपळा",
    hinglishName: "Bhopala",
  },
  { id: 19, englishName: "Radish", marathiName: "मूळा", hinglishName: "Mula" },
  { id: 20, englishName: "Beetroot", marathiName: "बीट", hinglishName: "Beet" },
  {
    id: 21,
    englishName: "Spring Onion",
    marathiName: "पात",
    hinglishName: "Paat",
  },
  {
    id: 22,
    englishName: "Sweet Corn",
    marathiName: "मक्याचे दाणे",
    hinglishName: "Makyache Daane",
  },
  {
    id: 23,
    englishName: "Green Chilli",
    marathiName: "हिरवी मिरची",
    hinglishName: "Mirchi",
  },
  {
    id: 24,
    englishName: "Red Chilli",
    marathiName: "लाल मिरची",
    hinglishName: "Laal Mirchi",
  },
  {
    id: 25,
    englishName: "Cucumber",
    marathiName: "काकडी",
    hinglishName: "Kakdi",
  },
  {
    id: 26,
    englishName: "Snake Gourd",
    marathiName: "पडवळ",
    hinglishName: "Parwal",
  },
  {
    id: 27,
    englishName: "Ridge Gourd",
    marathiName: "दोडका",
    hinglishName: "Dodka",
  },
  {
    id: 28,
    englishName: "Cluster Beans",
    marathiName: "गवार",
    hinglishName: "Gawar",
  },

  {
    id: 30,
    englishName: "Raw Banana",
    marathiName: "कच्चे केळं",
    hinglishName: "Kacche Kela",
  },
  { id: 31, englishName: "Yam", marathiName: "सुरण", hinglishName: "Suran" },

  {
    id: 33,
    englishName: "Turnip",
    marathiName: "शलगम",
    hinglishName: "Shalgam",
  },
  {
    id: 34,
    englishName: "Broccoli",
    marathiName: "ब्रोकली",
    hinglishName: "Broccoli",
  },
  {
    id: 35,
    englishName: "Mushroom",
    marathiName: "मशरूम",
    hinglishName: "Mushroom",
  },
  {
    id: 36,
    englishName: "Zucchini",
    marathiName: "झुकिनी",
    hinglishName: "Zucchini",
  },

  {
    id: 38,
    englishName: "Leek",
    marathiName: "पात (leek)",
    hinglishName: "Paat (leek)",
  },
  {
    id: 39,
    englishName: "Dill Leaves",
    marathiName: "शेपू",
    hinglishName: "Shepu",
  },

  {
    id: 43,
    englishName: "Curry Leaves",
    marathiName: "कढीपत्ता",
    hinglishName: "Kadhi Patta",
  },
  {
    id: 44,
    englishName: "Mint",
    marathiName: "पुदिना",
    hinglishName: "Pudina",
  },
  {
    id: 45,
    englishName: "Sweet Potato",
    marathiName: "राताळं",
    hinglishName: "Ratal",
  },
  {
    id: 46,
    englishName: "Ash Gourd",
    marathiName: "पांढरा भोपळा",
    hinglishName: "Pandhra Bhopala",
  },
  {
    id: 47,
    englishName: "Raw Mango",
    marathiName: "कैरी",
    hinglishName: "Kairi",
  },
  {
    id: 49,
    englishName: "Raw Papaya",
    marathiName: "कच्चा पपई",
    hinglishName: "Kaccha Papayi",
  },
  {
    id: 50,
    englishName: "Amaranth Leaves",
    marathiName: "पोकरा भाजी",
    hinglishName: "Pokara Bhaji",
  },
  {
    id: 51,
    englishName: "Red Amaranth",
    marathiName: "लाल भाजी",
    hinglishName: "Lal Bhaji",
  },
  {
    id: 52,
    englishName: "Rajgira",
    marathiName: "राजगिरा",
    hinglishName: "Rajgira",
  },
  {
    id: 53,
    englishName: "Chawli Leaves",
    marathiName: "चवळी भाजी",
    hinglishName: "Chawadi Bhaji",
  },
  { id: 54, englishName: "Lemon", marathiName: "लिंबू", hinglishName: "Limbu" },
  {
    id: 55,
    englishName: "Java Plum",
    marathiName: "जांभूळ",
    hinglishName: "Jambul",
  },
  {
    id: 56,
    englishName: "Custard Apple",
    marathiName: "सीताफळ",
    hinglishName: "Sitafal",
  },
  {
    id: 57,
    englishName: "Bullock's Heart",
    marathiName: "रामफळ",
    hinglishName: "Ramfal",
  },
  { id: 58, englishName: "Guava", marathiName: "पेरू", hinglishName: "Peru" },
  { id: 59, englishName: "Jujube", marathiName: "बोर", hinglishName: "Bor" },
  {
    id: 60,
    englishName: "Jackfruit",
    marathiName: "फणस",
    hinglishName: "Fanas",
  },
  {
    id: 61,
    englishName: "Field Beans",
    marathiName: "वाल",
    hinglishName: "Wal",
  },
  {
    id: 62,
    englishName: "Pigeon Pea",
    marathiName: "तूर",
    hinglishName: "Tur",
  },
  {
    id: 63,
    englishName: "Sliced Onion",
    marathiName: "कांदा चोप",
    hinglishName: "Kanda Chop",
  },
  {
    id: 64,
    englishName: "Ghor Bhaji",
    marathiName: "घोर भाजी",
    hinglishName: "Ghor Bhaji",
  },
  {
    id: 65,
    englishName: "Khel Bhaji",
    marathiName: "खेल भाजी",
    hinglishName: "Khel Bhaji",
  },
  {
    id: 66,
    englishName: "Khapar Khuti",
    marathiName: "खापरखुटी",
    hinglishName: "Khaprkhuti",
  },
  {
    id: 67,
    englishName: "Methi Bhaji",
    marathiName: "मेथी भाजी",
    hinglishName: "Methi Bhaji",
  },
  {
    id: 68,
    englishName: "Kakali",
    marathiName: "ककली",
    hinglishName: "Kakali",
  },
  {
    id: 69,
    englishName: "Dhemasa",
    marathiName: "धेमासा",
    hinglishName: "Dhemasa",
  },
  {
    id: 70,
    englishName: "Lawaki",
    marathiName: "लावकी",
    hinglishName: "Lawaki",
  },
  {
    id: 71,
    englishName: "Ash Gourd",
    marathiName: "कोहळा",
    hinglishName: "Kohala",
  },
  {
    id: 72,
    englishName: "Dhawali Bhaji",
    marathiName: "धवळी भाजी",
    hinglishName: "Dhawali Bhaji",
  },
  {
    id: 73,
    englishName: "Peanut",
    marathiName: "शेंगदाणा",
    hinglishName: "Mungfalli",
  },
  {
    id: 74,
    englishName: "Bengal Gram",
    marathiName: "हरभरा",
    hinglishName: "Chana",
  },
  {
    id: 75,
    englishName: "Sorrel Leaves",
    marathiName: "अंबाडी",
    hinglishName: "Ambadi",
  },
  {
    id: 76,
    englishName: "Kohlrabi",
    marathiName: "नवलकोल",
    hinglishName: "Navalkol",
  },
  {
    id: 77,
    englishName: "Radish",
    marathiName: "मुळा",
    hinglishName: "Mula",
  },
  {
    id: 78,
    englishName: "Green Peas",
    marathiName: "वाटाणा",
    hinglishName: "Vatana",
  },
  {
    id: 79,
    englishName: "Sambar (Dish)",
    marathiName: "सांबार ",
    hinglishName: "Sambar (Dish)",
  },
  {
    id: 80,
    englishName: "Tondaru",
    marathiName: "टोण्डरू ",
    hinglishName: "Tondaru",
  },
];

export default ProductList;
