const ProductList = [
  {
    id: 1,
    englishName: "Tomato",
    marathiName: "टोमॅटो",
    hinglishName: "TomaTo",
  },
  {
    id: 2,
    englishName: "Potato",
    marathiName: "बटाटा",
    hinglishName: "Batata",
  },
  { id: 3, englishName: "Onion", marathiName: "कांदा", hinglishName: "Kanda" },
  { id: 4, englishName: "Carrot", marathiName: "गाजर", hinglishName: "Gajar" },
  {
    id: 5,
    englishName: "Brinjal",
    marathiName: "वांगी",
    hinglishName: "Vaangi",
  },
  { id: 6, englishName: "Cabbage", marathiName: "कोबी", hinglishName: "Kobi" },
  {
    id: 7,
    englishName: "Cauliflower",
    marathiName: "फूलकोबी",
    hinglishName: "Phoolkobi",
  },
  {
    id: 8,
    englishName: "Green Peas",
    marathiName: "हिरवे वाटाणे",
    hinglishName: "Hirve Wataane",
  },
  {
    id: 9,
    englishName: "Spinach",
    marathiName: "पालक",
    hinglishName: "PaalaK",
  },
  {
    id: 10,
    englishName: "Fenugreek",
    marathiName: "मेथी",
    hinglishName: "Methi",
  },
  {
    id: 11,
    englishName: "Coriander",
    marathiName: "कोथिंबीर",
    hinglishName: "Kothimbir",
  },
  { id: 12, englishName: "Garlic", marathiName: "लसूण", hinglishName: "Lasun" },
  { id: 13, englishName: "Ginger", marathiName: "आले", hinglishName: "Aale" },
  {
    id: 14,
    englishName: "Bottle Gourd",
    marathiName: "दूधी भोपळा",
    hinglishName: "Doodhi Bhopala",
  },
  {
    id: 15,
    englishName: "Bitter Gourd",
    marathiName: "कारले",
    hinglishName: "Karle",
  },
  {
    id: 16,
    englishName: "Lady Finger",
    marathiName: "भेंडी",
    hinglishName: "Bhendi",
  },
  {
    id: 17,
    englishName: "Drumstick",
    marathiName: "शेवग्याच्या शेंगा",
    hinglishName: "Shevgyachya Shengaa",
  },
  {
    id: 18,
    englishName: "Pumpkin",
    marathiName: "भोपळा",
    hinglishName: "Bhopala",
  },
  { id: 19, englishName: "Radish", marathiName: "मूळा", hinglishName: "Mula" },
  { id: 20, englishName: "Beetroot", marathiName: "बीट", hinglishName: "Beet" },
  {
    id: 21,
    englishName: "Spring Onion",
    marathiName: "पात",
    hinglishName: "Paat",
  },
  {
    id: 22,
    englishName: "Sweet Corn",
    marathiName: "मक्याचे दाणे",
    hinglishName: "Makyache Daane",
  },
  {
    id: 23,
    englishName: "Green Chilli",
    marathiName: "हिरवी मिरची",
    hinglishName: "Hirvi Mirchi",
  },
  {
    id: 24,
    englishName: "Red Chilli",
    marathiName: "लाल मिरची",
    hinglishName: "Laal Mirchi",
  },
  {
    id: 25,
    englishName: "Cucumber",
    marathiName: "काकडी",
    hinglishName: "Kakdi",
  },
  {
    id: 26,
    englishName: "Snake Gourd",
    marathiName: "पडवळ",
    hinglishName: "Padwal",
  },
  {
    id: 27,
    englishName: "Ridge Gourd",
    marathiName: "दोडका",
    hinglishName: "Dodka",
  },
  {
    id: 28,
    englishName: "Cluster Beans",
    marathiName: "गवार",
    hinglishName: "Gawar",
  },
  {
    id: 29,
    englishName: "French Beans",
    marathiName: "फ्रेंच बीन",
    hinglishName: "French Bean",
  },
  {
    id: 30,
    englishName: "Raw Banana",
    marathiName: "कच्चे केळं",
    hinglishName: "Kacche Kela",
  },
  { id: 31, englishName: "Yam", marathiName: "सुरण", hinglishName: "Suran" },
  {
    id: 32,
    englishName: "Taro Root",
    marathiName: "अळकुडी",
    hinglishName: "Alkudi",
  },
  {
    id: 33,
    englishName: "Turnip",
    marathiName: "शलगम",
    hinglishName: "Shalgam",
  },
  {
    id: 34,
    englishName: "Broccoli",
    marathiName: "ब्रोकली",
    hinglishName: "Broccoli",
  },
  {
    id: 35,
    englishName: "Mushroom",
    marathiName: "मशरूम",
    hinglishName: "Mushroom",
  },
  {
    id: 36,
    englishName: "Zucchini",
    marathiName: "झुकिनी",
    hinglishName: "Zucchini",
  },
  {
    id: 37,
    englishName: "Celery",
    marathiName: "अजमोदा",
    hinglishName: "Ajmoda",
  },
  {
    id: 38,
    englishName: "Leek",
    marathiName: "पात (leek)",
    hinglishName: "Paat (leek)",
  },
  {
    id: 39,
    englishName: "Dill Leaves",
    marathiName: "शेपू",
    hinglishName: "Shepu",
  },
  {
    id: 40,
    englishName: "Amaranth",
    marathiName: "तांदुळजा",
    hinglishName: "Tandulja",
  },
  {
    id: 41,
    englishName: "Sorghum Leaves",
    marathiName: "ज्वारीचे पान",
    hinglishName: "Jwariche Paan",
  },
  {
    id: 42,
    englishName: "Mustard Leaves",
    marathiName: "मोहरीची पाने",
    hinglishName: "Moharichi Pane",
  },
  {
    id: 43,
    englishName: "Curry Leaves",
    marathiName: "कढीपत्ता",
    hinglishName: "Kadhi Patta",
  },
  {
    id: 44,
    englishName: "Mint",
    marathiName: "पुदिना",
    hinglishName: "Pudina",
  },
  {
    id: 45,
    englishName: "Sweet Potato",
    marathiName: "राताळं",
    hinglishName: "Ratal",
  },
  {
    id: 46,
    englishName: "Ash Gourd",
    marathiName: "पांढरा भोपळा",
    hinglishName: "Pandhra Bhopala",
  },
  {
    id: 47,
    englishName: "Raw Mango",
    marathiName: "कैरी",
    hinglishName: "Kairi",
  },
  {
    id: 48,
    englishName: "Green Tomato",
    marathiName: "हिरवा टोमॅटो",
    hinglishName: "Hirva Tomato",
  },
  {
    id: 49,
    englishName: "Raw Papaya",
    marathiName: "कच्चा पपई",
    hinglishName: "Kaccha Papayi",
  },
  {
    id: 50,
    englishName: "Turmeric Root",
    marathiName: "हळद मूळ",
    hinglishName: "Halad Mul",
  },
];

export default ProductList;
